version: "3.8"
services:
  discord-bot:
    restart: "always"
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./config.json:/app/config.json
      - /var/log/discordbot.log:/app/combined.log
