version: "3.8"
services:
  discord-bot:
    restart: "always"
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ${PWD}/config.json:/app/config.json
      - ${PWD}/pressCounter.json:/app/pressCounter.json
      - /var/log/discordbot.log:/app/combined.log
